name: bluetooth_low_energy
description: A Flutter plugin for controlling the bluetooth low energy, supports central and peripheral apis.
version: 5.0.0-dev.3
homepage: https://github.com/yanshouwang/bluetooth_low_energy

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  bluetooth_low_energy_platform_interface: ^5.0.0-dev.10
  bluetooth_low_energy_android: ^5.0.0-dev.4
  bluetooth_low_energy_darwin: ^5.0.0-dev.1
  bluetooth_low_energy_windows: ^5.0.0-dev.7
  bluetooth_low_energy_linux: ^5.0.0-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: bluetooth_low_energy_android
      ios:
        default_package: bluetooth_low_energy_darwin
      macos:
        default_package: bluetooth_low_energy_darwin
      windows:
        default_package: bluetooth_low_energy_windows
      linux:
        default_package: bluetooth_low_energy_linux
