name: bluetooth_low_energy
description: A Flutter plugin for controlling the bluetooth low energy.
version: 3.0.0-dev.4
homepage: https://github.com/yanshouwang/bluetooth_low_energy

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  bluetooth_low_energy_platform_interface: ^3.0.0-dev.5
  bluetooth_low_energy_android: ^3.0.0-dev.6
  bluetooth_low_energy_darwin: ^3.0.0-dev.4
  bluetooth_low_energy_linux: ^3.0.0-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: bluetooth_low_energy_android
      ios:
        default_package: bluetooth_low_energy_darwin
      macos:
        default_package: bluetooth_low_energy_darwin
      linux:
        default_package: bluetooth_low_energy_linux
