name: bluetooth_low_energy
description: A Flutter plugin for controlling the bluetooth low energy.
version: 3.0.0
homepage: https://github.com/yanshouwang/bluetooth_low_energy

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  # bluetooth_low_energy_platform_interface: ^2.2.0
  # bluetooth_low_energy_android: ^2.2.1
  # bluetooth_low_energy_darwin: ^2.2.0
  # bluetooth_low_energy_linux: ^2.2.0
  # bluetooth_low_energy_windows: ^2.2.0
  bluetooth_low_energy_platform_interface:
    path: ../bluetooth_low_energy_platform_interface
  bluetooth_low_energy_android:
    path: ../bluetooth_low_energy_android
  bluetooth_low_energy_darwin:
    path: ../bluetooth_low_energy_darwin
  bluetooth_low_energy_linux:
    path: ../bluetooth_low_energy_linux
  bluetooth_low_energy_windows:
    path: ../bluetooth_low_energy_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: bluetooth_low_energy_android
      ios:
        default_package: bluetooth_low_energy_darwin
      macos:
        default_package: bluetooth_low_energy_darwin
      linux:
        default_package: bluetooth_low_energy_linux
      windows:
        default_package: bluetooth_low_energy_windows
