name: bluetooth_low_energy
description: "A Flutter plugin for controlling the bluetooth low energy, supports central and peripheral roles."
version: 6.0.0-dev.0
homepage: "https://github.com/yanshouwang/bluetooth_low_energy"
repository: "https://github.com/yanshouwang/bluetooth_low_energy"
issue_tracker: "https://github.com/yanshouwang/bluetooth_low_energy/issues"
topics:
  - bluetooth
  - bluetooth-low-energy
  - ble

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  bluetooth_low_energy_platform_interface: ^6.0.0-dev.16
  bluetooth_low_energy_android: ^6.0.0-dev.2
  bluetooth_low_energy_darwin: ^6.0.0-dev.0
  bluetooth_low_energy_windows: ^6.0.0-dev.6
  bluetooth_low_energy_linux: ^6.0.0-dev.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: bluetooth_low_energy_android
      ios:
        default_package: bluetooth_low_energy_darwin
      macos:
        default_package: bluetooth_low_energy_darwin
      windows:
        default_package: bluetooth_low_energy_windows
      linux:
        default_package: bluetooth_low_energy_linux
