name: bluetooth_low_energy_android
description: "Android implementation of the bluetooth_low_energy plugin."
version: 6.0.0-dev.0
homepage: "https://github.com/yanshouwang/bluetooth_low_energy"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bluetooth_low_energy_platform_interface: ^6.0.0-dev.2
  jni: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  pigeon: ^18.0.0
  jnigen: ^0.9.0

flutter:
  plugin:
    implements: bluetooth_low_energy
    platforms:
      android:
        package: dev.yanshouwang.bluetooth_low_energy_android
        pluginClass: BluetoothLowEnergyAndroidPlugin
        dartPluginClass: BluetoothLowEnergyAndroidPlugin
